on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code & setup version 14 of Java
    -   uses: actions/checkout@v2

    -   name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      # Run all maven phases to deployment
      # with our repository as a target
    -   name: Publish jar to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}