on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # Build maven target and save result
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Cache maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build using Maven
      run: mvn clean package

    - name: Save result
      uses: actions/upload-artifact@v1
      with:
        name: build-result
        path: target
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./target/site/jacoco/jacoco.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  # Package and publish jar on github packages
  package-jar:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load result
        uses: actions/download-artifact@v1
        with:
          name: build-result
          path: target

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Publish jar to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISTRIBUTION_ID: github
          DISTRIBUTION_NAME: BEP LingoWords
          DISTRIBUTION_URL: https://maven.pkg.github.com/${{ github.repository }}
